run:
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: false
issues:
  exclude-dirs:
    - examples/
linters:
  enable-all: true
  disable:
    - depguard
    - execinquery
    - exportloopref
    - gofumpt
    - gomnd
    - nlreturn
    - wrapcheck
    - wsl
